export const navLinks = [
  { label: 'Home', href: '/' },
  { label: 'About us', href: '/about-us' },
  { label: 'Community', href: '/community' },
  { label: 'Advertise', href: '/advertise' },
  {
    label: 'Schedule',
    href: '/schedule',
    // subMenu: [
    //   { label: 'Punjabi Top 10', href: '/schedule/punjabi-top-10' },
    //   { label: 'Bhangra Nation', href: '/schedule/bhangra-nation' },
    //   { label: 'Apna Punjab', href: '/schedule/apna-punjab' },
    //   { label: 'Treanding Top 20', href: '/schedule/treanding-top-20' },
    //   { label: 'Desi Grooves', href: '/schedule/desi-grooves' },
    //   { label: 'Sur O Khotha', href: '/schedule/sur-o-khotha' },
    //   { label: 'Bollywood Hungama', href: '/schedule/bollywood-hungama' },
    //   { label: 'Harano Sur', href: '/schedule/harano-sur' },
    //   { label: 'Slice of Life - Gujarati', href: '/schedule/slice-of-life-gujarati' },
    //   { label: 'Hi on Chai', href: '/schedule/hi-on-chai' },
    //   { label: 'Zabban-e-Dil', href: '/schedule/zabban-e-dil' },
    //   { label: 'Tan Tana Ten', href: '/schedule/tan-tana-ten' },
    // ],
  },
  { label: 'Journal', href: '/journal' },
  {
    label: 'Meet Our Hosts',
    href: '/meet-our-hosts',
    subMenu: [
      { label: 'RJ Devang', href: '/meet-our-hosts/rj-devang' },
      { label: 'Tanzila Anis', href: '/meet-our-hosts/tanzila-anis' },
      // { label: 'Rj Manali', href: '/meet-our-hosts/rj-manali' },
      { label: 'Iqbal Atwal', href: '/meet-our-hosts/iqbal-atwal' },
      { label: 'Nasreen Shoshi', href: '/meet-our-hosts/nasreen-shoshi' },
      // { label: 'Praveen Lata', href: '/meet-our-hosts/praveen-lata' },
      { label: 'Meenal', href: '/meet-our-hosts/meenal' },
      { label: 'Vandana Kurichh', href: '/meet-our-hosts/vandana-kurichh' },
      { label: 'Rj Glen', href: '/meet-our-hosts/rj-glen' },
      { label: 'Rj Aashish', href: '/meet-our-hosts/rj-aashish' },
    ],
  },
  { label: 'Charter', href: '/charter' },
  { label: 'Jobs', href: '/jobs' },
  { label: 'Contact', href: '/contact' },
  { label: 'Media', href: '/media' },
  { label: 'Gallery', href: '/gallery' },
]
