export const navLinks = [
  { label: 'Home', href: '/' },
  { label: 'About us', href: '/about-us' },
  { label: 'Community', href: '/community' },
  { label: 'Advertise', href: '/advertise' },
  { label: 'Schedule', href: '/schedule' },
  { label: 'Journal', href: '/journal' },
  {
    label: 'Meet Our Hosts',
    href: '/meet-our-hosts',
    subMenu: [
      { label: 'RJ Devang', href: '/meet-our-hosts/rj-devang' },
      { label: 'Tanzila Anis', href: '/meet-our-hosts/tanzila-anis' },
      // { label: 'Rj Manali', href: '/meet-our-hosts/rj-manali' },
      { label: 'Iqbal Atwal', href: '/meet-our-hosts/iqbal-atwal' },
      { label: 'Nasreen Shoshi', href: '/meet-our-hosts/nasreen-shoshi' },
      // { label: 'Praveen Lata', href: '/meet-our-hosts/praveen-lata' },
      { label: 'Meenal', href: '/meet-our-hosts/meenal' },
      { label: 'Vandana Kurichh', href: '/meet-our-hosts/vandana-kurichh' },
      { label: 'Rj Glen', href: '/meet-our-hosts/rj-glen' },
      { label: 'Rj Aashish', href: '/meet-our-hosts/rj-aashish' },
    ],
  },
  { label: 'Charter', href: '/charter' },
  { label: 'Jobs', href: '/jobs' },
  { label: 'Contact', href: '/contact' },
  { label: 'Media', href: '/media' },
  { label: 'Gallery', href: '/gallery' },
]
