/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    schedule: Schedule;
    audio: Audio;
    Jobs: Job;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    schedule: ScheduleSelect<false> | ScheduleSelect<true>;
    audio: AudioSelect<false> | AudioSelect<true>;
    Jobs: JobsSelect<false> | JobsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            /**
             * Optional. If left blank, the title of the page will display.
             */
            title?: string | null;
            /**
             * Highlight text by surrounding it with asterisks (*).
             */
            headline: string;
            image: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'banner';
          }
        | {
            /**
             * Highlight text by surrounding it with asterisks (*).
             */
            heading: string;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentSection';
          }
        | {
            title?: string | null;
            layout: 'list' | 'slider';
            id?: string | null;
            blockName?: string | null;
            blockType: 'scheduleSection';
          }
        | {
            body: string;
            colourScheme: 'beigeOnHighlight' | 'highlightOnYellow' | 'highlightOnBeige';
            id?: string | null;
            blockName?: string | null;
            blockType: 'highlightTextSection';
          }
        | {
            image?: (string | null) | Media;
            /**
             * Choose whether image appears left or right
             */
            imagePosition?: ('right' | 'left') | null;
            heading: string;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'community-section';
          }
        | {
            image: string | Media;
            overlay?: boolean | null;
            overlayOpacity?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-banner';
          }
        | {
            heading: string;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            button?: {
              text?: string | null;
              url?: string | null;
            };
            image: string | Media;
            /**
             * Choose whether image appears left or right
             */
            imagePosition?: ('right' | 'left') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'halves-section';
          }
        | {
            quote: string;
            author: string;
            colorScheme: 'beige-on-highlight' | 'highlight-on-yellow' | 'highlight-on-beige';
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonial';
          }
        | {
            slides?:
              | {
                  images: (string | Media)[];
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'slides';
          }
        | {
            displayType: 'list' | 'slider';
            videos: {
              title?: string | null;
              youtubeUrl: string;
              date?: string | null;
              thumbnail?: (string | null) | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'VideoGallery';
          }
        | {
            title: string;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            organizations?:
              | {
                  name: string;
                  logo: string | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'supportPromotion';
          }
        | {
            title: string;
            description?: string | null;
            sponsors?:
              | {
                  logo: string | Media;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            ctaText?: string | null;
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sponsors';
          }
        | {
            subtitle?: string | null;
            title: string;
            packages?:
              | {
                  name: string;
                  price: string;
                  duration?: string | null;
                  /**
                   * Example: #E8A64D
                   */
                  backgroundColor?: string | null;
                  features?:
                    | {
                        featureKey?: string | null;
                        featureValue?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'packages';
          }
        | {
            cards?:
              | {
                  category: 'events' | 'memories' | 'spotlight' | 'updates';
                  date?: string | null;
                  title: string;
                  slug: string;
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  image?: (string | null) | Media;
                  video?: {
                    /**
                     * Upload video file
                     */
                    upload?: (string | null) | Media;
                    /**
                     * Paste YouTube, Vimeo, or external video URL
                     */
                    url?: string | null;
                  };
                  /**
                   * Thumbnail image for video
                   */
                  videoThumbnail?: (string | null) | Media;
                  linkText?: string | null;
                  link?: string | null;
                  audio?: (string | null) | Audio;
                  /**
                   * Used if image is not provided (#EDE2CF)
                   */
                  backgroundColor?: string | null;
                  /**
                   * Text color for card content (#1F3A44)
                   */
                  textColor?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'filterCardsBlock';
          }
        | {
            image?: (string | null) | Media;
            /**
             * Choose whether image appears left or right
             */
            imagePosition?: ('right' | 'left') | null;
            heading: string;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'host-section';
          }
        | {
            jobs: (string | Job)[];
            image?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'jobsBlock';
          }
        | {
            interviews?:
              | {
                  image?: (string | null) | Media;
                  audio?: (string | null) | Audio;
                  title: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'InterviewBlock';
          }
        | {
            images?:
              | {
                  image: string | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGallery';
          }
        | {
            title: string;
            description?: string | null;
            images?:
              | {
                  image: string | Media;
                  size?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio".
 */
export interface Audio {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Jobs".
 */
export interface Job {
  id: string;
  title: string;
  Description: string;
  JobTitle: string;
  slug: string;
  JobDescription: string;
  location: string;
  Salary: string;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule".
 */
export interface Schedule {
  id: string;
  title: string;
  shortDescription: string;
  dj: string;
  image: string | Media;
  day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
  startTime: string;
  endTime: string;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'schedule';
        value: string | Schedule;
      } | null)
    | ({
        relationTo: 'audio';
        value: string | Audio;
      } | null)
    | ({
        relationTo: 'Jobs';
        value: string | Job;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        banner?:
          | T
          | {
              title?: T;
              headline?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        contentSection?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        scheduleSection?:
          | T
          | {
              title?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        highlightTextSection?:
          | T
          | {
              body?: T;
              colourScheme?: T;
              id?: T;
              blockName?: T;
            };
        'community-section'?:
          | T
          | {
              image?: T;
              imagePosition?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        'image-banner'?:
          | T
          | {
              image?: T;
              overlay?: T;
              overlayOpacity?: T;
              id?: T;
              blockName?: T;
            };
        'halves-section'?:
          | T
          | {
              heading?: T;
              body?: T;
              button?:
                | T
                | {
                    text?: T;
                    url?: T;
                  };
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        testimonial?:
          | T
          | {
              quote?: T;
              author?: T;
              colorScheme?: T;
              id?: T;
              blockName?: T;
            };
        slides?:
          | T
          | {
              slides?:
                | T
                | {
                    images?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        VideoGallery?:
          | T
          | {
              displayType?: T;
              videos?:
                | T
                | {
                    title?: T;
                    youtubeUrl?: T;
                    date?: T;
                    thumbnail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        supportPromotion?:
          | T
          | {
              title?: T;
              body?: T;
              organizations?:
                | T
                | {
                    name?: T;
                    logo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        sponsors?:
          | T
          | {
              title?: T;
              description?: T;
              sponsors?:
                | T
                | {
                    logo?: T;
                    link?: T;
                    id?: T;
                  };
              ctaText?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        packages?:
          | T
          | {
              subtitle?: T;
              title?: T;
              packages?:
                | T
                | {
                    name?: T;
                    price?: T;
                    duration?: T;
                    backgroundColor?: T;
                    features?:
                      | T
                      | {
                          featureKey?: T;
                          featureValue?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        filterCardsBlock?:
          | T
          | {
              cards?:
                | T
                | {
                    category?: T;
                    date?: T;
                    title?: T;
                    slug?: T;
                    content?: T;
                    image?: T;
                    video?:
                      | T
                      | {
                          upload?: T;
                          url?: T;
                        };
                    videoThumbnail?: T;
                    linkText?: T;
                    link?: T;
                    audio?: T;
                    backgroundColor?: T;
                    textColor?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'host-section'?:
          | T
          | {
              image?: T;
              imagePosition?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        jobsBlock?:
          | T
          | {
              jobs?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        InterviewBlock?:
          | T
          | {
              interviews?:
                | T
                | {
                    image?: T;
                    audio?: T;
                    title?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              description?: T;
              images?:
                | T
                | {
                    image?: T;
                    size?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule_select".
 */
export interface ScheduleSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  dj?: T;
  image?: T;
  day?: T;
  startTime?: T;
  endTime?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio_select".
 */
export interface AudioSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  Description?: T;
  JobTitle?: T;
  slug?: T;
  JobDescription?: T;
  location?: T;
  Salary?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}